---
title: "1980 Team Homeruns"
author: "Justin Minsk"
date: "2017-09-27"
tags: ["R", "ggplots", "ggiraph"]
catagory: ["R"]
---

Import libraries:

```{r message=FALSE, warning=FALSE}
library(Lahman)
library(dplyr)
library(ggplot2)
library(ggiraph)
```

Set up the data:

```{r}

df<-Teams%>%
  filter(yearID == 1980)%>%
  select(name, HR)%>%
  arrange(HR)

#sort the teams from lahman by the year 1980 and show the name and HR total

df$name<-factor(df$name, levels = df$name)

#change the type of data to a factor and not a chr, then level it by our dplyr querry 
```

Create an interactive graph with ggiraph:

```{r}
g<-ggplot() +
  geom_bar_interactive(data = df, aes(x = name, y = HR, tooltip = HR, data_id = name), stat = "identity", color = "blue", fill = "white") +
  coord_flip()+
  ggtitle("1980 Team Homeruns")+
  ylab("Homeruns")+
  xlab("Team Name")

#graph the data using a bar graph

ggiraph(code = print(g), hover_css = "fill:red;stroke:black")

#use ggiraph to make it interactive showing the hr on hover 
```

