---
title: "Changing data types using dplyr"
author: "Justin Minsk"
date: "2017-09-25"
tags: ["R", "ggplots", "dplyr"]
catagory: ["R"]
---

Showing how to sort data using dyplr to make ggplots show a graph that it would not without changing the data type.

Load libraries:

```{r message=FALSE, warning=FALSE}
library(Lahman)
library(dplyr)
library(ggplot2)
```

Change the data with dyplr:

```{r}

df<-Teams%>%
  filter(yearID == 1980)%>%
  select(name, HR)%>%
  arrange(HR)

#sort the teams from lahman by the year 1980 and show the name and HR total

class(df$name)

#look at the data type of name in the data frame

```


```{r}
df$name<-factor(df$name, levels = df$name)

#change the type of data to a factor and not a chr, then level it by our dplyr querry

class(df$name)

#looking at the data type again
```

Graph the data:

```{r}
ggplot() +
  geom_bar(data = df, aes(x = name, y = HR), stat = "identity", color = "blue", fill = "white") +
  coord_flip()

#graph the data using a bar graph
```

